### ISSUE TITLE
Port forwarding failure in IPtester and 503 service unavailable in UPtester

### ISSUE THREAD

**Issue by Priyansh2** [matejbasic/PythonScrapyBasicSetup#5]

**Comment by Priyansh2** [comment]
I follow the exact steps and tried running `python3 run.py` [Had done suitable library modification according to python3 and also resolved the problem according to #4 ]. It throws me following error :- 

```
2018-09-19 17:42:34 [scrapy.crawler] INFO: Overridden settings: {'RETRY_HTTP_CODES': [500, 502, 503, 504], 'DNS_TIMEOUT': 10, 'DOWNLOAD_TIMEOUT': 24, 'CONCURRENT_REQUESTS': 32, 'COOKIES_ENABLED': False, 'NEWSPIDER_MODULE': 'PythonScrapyBasicSetup.spiders', 'TELNETCONSOLE_ENABLED': False, 'BOT_NAME': 'PythonScrapyBasicSetup', 'SPIDER_MODULES': ['PythonScrapyBasicSetup.spiders']}
2018-09-19 17:42:35 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.logstats.LogStats',
 'scrapy.extensions.memusage.MemoryUsage']
2018-09-19 17:42:35 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'PythonScrapyBasicSetup.middlewares.user_agent.RandomUserAgentMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'PythonScrapyBasicSetup.middlewares.proxy.TorProxyMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2018-09-19 17:42:35 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2018-09-19 17:42:35 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2018-09-19 17:42:35 [scrapy.core.engine] INFO: Spider opened
2018-09-19 17:42:35 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2018-09-19 17:42:35 [root] INFO: Using proxy: http://127.0.0.1:8118
2018-09-19 17:42:35 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://icanhazip.com> (failed 1 times): Could not open CONNECT tunnel with proxy 127.0.0.1:8118 [{'reason': b'Forwarding failure', 'status': 503}]
2018-09-19 17:42:35 [root] INFO: Using proxy: http://127.0.0.1:8118
2018-09-19 17:42:35 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET https://icanhazip.com> (failed 2 times): Could not open CONNECT tunnel with proxy 127.0.0.1:8118 [{'reason': b'Forwarding failure', 'status': 503}]
2018-09-19 17:42:35 [root] INFO: Using proxy: http://127.0.0.1:8118
2018-09-19 17:42:35 [scrapy.downloadermiddlewares.retry] DEBUG: Gave up retrying <GET https://icanhazip.com> (failed 3 times): Could not open CONNECT tunnel with proxy 127.0.0.1:8118 [{'reason': b'Forwarding failure', 'status': 503}]
2018-09-19 17:42:35 [scrapy.core.scraper] ERROR: Error downloading <GET https://icanhazip.com>
Traceback (most recent call last):
  File "/home/priyansh/.local/lib/python3.5/site-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/priyansh/.local/lib/python3.5/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/priyansh/.local/lib/python3.5/site-packages/scrapy/core/downloader/middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
scrapy.core.downloader.handlers.http11.TunnelError: Could not open CONNECT tunnel with proxy 127.0.0.1:8118 [{'reason': b'Forwarding failure', 'status': 503}]
2018-09-19 17:42:35 [scrapy.core.engine] INFO: Closing spider (finished)
2018-09-19 17:42:35 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/exception_count': 3,
 'downloader/exception_type_count/scrapy.core.downloader.handlers.http11.TunnelError': 3,
 'downloader/request_bytes': 939,
 'downloader/request_count': 3,
 'downloader/request_method_count/GET': 3,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2018, 9, 19, 12, 12, 35, 393817),
 'log_count/DEBUG': 3,
 'log_count/ERROR': 1,
 'log_count/INFO': 10,
 'memusage/max': 51724288,
 'memusage/startup': 51724288,
 'retry/count': 2,
 'retry/max_reached': 1,
 'retry/reason_count/scrapy.core.downloader.handlers.http11.TunnelError': 2,
 'scheduler/dequeued': 3,
 'scheduler/dequeued/memory': 3,
 'scheduler/enqueued': 3,
 'scheduler/enqueued/memory': 3,
 'start_time': datetime.datetime(2018, 9, 19, 12, 12, 35, 174077)}
2018-09-19 17:42:35 [scrapy.core.engine] INFO: Spider closed (finished)
2018-09-19 17:42:35 [scrapy.crawler] INFO: Overridden settings: {'RETRY_HTTP_CODES': [500, 502, 503, 504], 'DNS_TIMEOUT': 10, 'DOWNLOAD_TIMEOUT': 24, 'CONCURRENT_REQUESTS': 32, 'COOKIES_ENABLED': False, 'NEWSPIDER_MODULE': 'PythonScrapyBasicSetup.spiders', 'TELNETCONSOLE_ENABLED': False, 'BOT_NAME': 'PythonScrapyBasicSetup', 'SPIDER_MODULES': ['PythonScrapyBasicSetup.spiders']}
2018-09-19 17:42:35 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.logstats.LogStats',
 'scrapy.extensions.memusage.MemoryUsage']
2018-09-19 17:42:35 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'PythonScrapyBasicSetup.middlewares.user_agent.RandomUserAgentMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'PythonScrapyBasicSetup.middlewares.proxy.TorProxyMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2018-09-19 17:42:35 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2018-09-19 17:42:35 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2018-09-19 17:42:35 [scrapy.core.engine] INFO: Spider opened
2018-09-19 17:42:35 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2018-09-19 17:42:35 [root] INFO: Using proxy: http://127.0.0.1:8118
2018-09-19 17:42:35 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET http://whatsmyuseragent.org/> (failed 1 times): 503 Service Unavailable
2018-09-19 17:42:35 [root] INFO: Using proxy: http://127.0.0.1:8118
2018-09-19 17:42:35 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET http://whatsmyuseragent.org/> (failed 2 times): 503 Service Unavailable
2018-09-19 17:42:35 [root] INFO: Using proxy: http://127.0.0.1:8118
2018-09-19 17:42:35 [scrapy.downloadermiddlewares.retry] DEBUG: Gave up retrying <GET http://whatsmyuseragent.org/> (failed 3 times): 503 Service Unavailable
2018-09-19 17:42:35 [scrapy.core.engine] DEBUG: Crawled (503) <GET http://whatsmyuseragent.org/> (referer: None)
2018-09-19 17:42:35 [scrapy.spidermiddlewares.httperror] INFO: Ignoring response <503 http://whatsmyuseragent.org/>: HTTP status code is not handled or not allowed
2018-09-19 17:42:35 [scrapy.core.engine] INFO: Closing spider (finished)
2018-09-19 17:42:35 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 855,
 'downloader/request_count': 3,
 'downloader/request_method_count/GET': 3,
 'downloader/response_bytes': 24693,
 'downloader/response_count': 3,
 'downloader/response_status_count/503': 3,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2018, 9, 19, 12, 12, 35, 545422),
 'httperror/response_ignored_count': 1,
 'httperror/response_ignored_status_count/503': 1,
 'log_count/DEBUG': 4,
 'log_count/INFO': 11,
 'memusage/max': 52895744,
 'memusage/startup': 52895744,
 'response_received_count': 1,
 'retry/count': 2,
 'retry/max_reached': 1,
 'retry/reason_count/503 Service Unavailable': 2,
 'scheduler/dequeued': 3,
 'scheduler/dequeued/memory': 3,
 'scheduler/enqueued': 3,
 'scheduler/enqueued/memory': 3,
 'start_time': datetime.datetime(2018, 9, 19, 12, 12, 35, 419917)}
2018-09-19 17:42:35 [scrapy.core.engine] INFO: Spider closed (finished)
```


Im new to this stuff and don't know anything related to networking stuff. Please help me to sort this. Meanwhile I also checked whether my tor is working or not. When i enter `tor` on cli it shows me this :- 



```
Sep 19 17:49:36.822 [notice] Tor 0.2.9.14 running on Linux with Libevent 2.0.21-stable, OpenSSL 1.0.2g and Zlib 1.2.8.
Sep 19 17:49:36.822 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Sep 19 17:49:36.822 [notice] Read configuration file "/etc/tor/torrc".
Sep 19 17:49:36.826 [notice] Opening Socks listener on 127.0.0.1:9050
Sep 19 17:49:36.826 [notice] Opening Control listener on 127.0.0.1:9051
Sep 19 17:49:36.000 [notice] Parsing GEOIP IPv4 file /usr/share/tor/geoip.
Sep 19 17:49:36.000 [notice] Parsing GEOIP IPv6 file /usr/share/tor/geoip6.
Sep 19 17:49:37.000 [notice] Bootstrapped 0%: Starting
Sep 19 17:49:37.000 [notice] Bootstrapped 45%: Asking for relay descriptors
Sep 19 17:50:48.000 [warn] Problem bootstrapping. Stuck at 45%: Asking for relay descriptors. (DONE; DONE; count 10; recommendation warn; host C7B6A1B76B6476DB3DA8C960E262CC7425B5C5F8 at 62.109.4.115:443)
Sep 19 17:50:48.000 [warn] 10 connections have failed:
Sep 19 17:50:48.000 [warn]  5 connections died in state handshaking (TLS) with SSL state SSLv2/v3 read server hello A in HANDSHAKE
Sep 19 17:50:48.000 [warn]  5 connections died in state connect()ing with SSL state (No SSL object).
```

EDIT:- The last four warning messages repeated again and again after this. 
Is this be the cause behind not working any of the spiders  ?

**Comment by matejbasic** [comment]
@Priyansh2 hi! Not quite sure what is happening, is there any chance to share your code or give me access to your machine if possible?

Matej,
mbasic3310@gmail.com

**Comment by Priyansh2** [comment]
@matejbasic here is my whole code base :- https://github.com/Priyansh2/PythonScrapyBasicSetup.

**Comment by Priyansh2** [comment]
@matejbasic It worked. There was some problem with the tor. I reinstalled it.
